version: '3'
services:
  nginx:
    image: nginx:6.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
