version: '3'
services:
  nginx:
    image: nginx:1.26.1
    ports:
      - "5678:5678"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx

    networks:
      default:
        ipv4_address: 192.16.1.2

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.16.1.0/24
