version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_NODENAME: TDMT_rabbitMQ
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    networks:
      default:
        ipv4_address: 192.16.1.2

volumes:
  rabbitmq_data: 
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.16.1.0/24
