version: '1'

services:
  tomcat:
    restart: always
    image: tomcat:latest
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./web.xml:/usr/local/tomcat/conf/web.xml:ro
      - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh:ro
      - ./webapp:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
    networks:
        default:
          ipv4_address: 192.16.1.2

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.16.1.0/24
      
