version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "443:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./certs:/certs
      - ./ldap.toml:/etc/grafana/ldap.toml
    environment:
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_HTTPS_PORT=443
      - GF_SECURITY_ADMIN_PASSWORD=your_admin_password
      - GF_SERVER_CERT_FILE=/certs/grafana.crt
      - GF_SERVER_KEY_FILE=/certs/grafana.key
      - GF_AUTH_LDAP_ENABLED=true
      - GF_AUTH_LDAP_CONFIG_FILE=/etc/grafana/ldap.toml
    restart: always

volumes:
  grafana-data:
