# /etc/grafana/ldap.toml

[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "ldap.example.com"

# Default port is 389 or 636 if use_ssl = true
port = 389

# Set to true if ldap server supports TLS
use_ssl = false

# Set to true if connect ldap server with STARTTLS pattern (create connection in insecure, then upgrade to secure connection with TLS)
start_tls = false

# set to true if you want to skip ssl cert validation
ssl_skip_verify = false

# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = "/path/to/certificate.crt"

# Search user bind dn
bind_dn = "cn=admin,dc=example,dc=com"

# Search user bind password
bind_password = 'password'

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
search_filter = "(uid=%s)"

# An array of base dns to search through
search_base_dns = ["dc=example,dc=com"]

# In POSIX LDAP schemas, without memberOf attribute
# If your LDAP server doesn't support memberOf or equivalent (like member or memberUid), set to true
search_request_username = "uid"

# Map ldap id to user name
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"

# Map ldap id to email
[[servers.group_mappings]]
group_dn = "cn=grafana_users,ou=groups,dc=example,dc=com"
org_role = "Viewer"
# The Grafana organization to add users to
org_id = 1

[[servers.group_mappings]]
group_dn = "cn=grafana_admins,ou=groups,dc=example,dc=com"
org_role = "Admin"
# The Grafana organization to add users to
org_id = 1
